/**
 * src/db/sessionRepository.ts
 *
 * Prisma repository for DoctorSession records.
 *
 * Every method gracefully no-ops (returns null/undefined) if the Prisma
 * client is unavailable — callers fall back to the in-memory store.
 */

import { type DoctorSession, type SessionStatus } from '@prisma/client';
import { getPrismaClient } from './prismaClient';

export type { DoctorSession };

export interface CreateSessionParams {
  id: string;      // UUID — pre-generated by the session route
  doctorId: string;
  expiresAt: Date;
  patientName?: string;
  patientAge?: number;
  preferredLanguage?: string;
}

/**
 * Persists a new triage session to the database.
 * Returns the created record, or null if DB is unavailable.
 */
export async function createSession(
  params: CreateSessionParams,
): Promise<DoctorSession | null> {
  const db = getPrismaClient();
  if (!db) return null;

  try {
    return await db.doctorSession.create({
      data: {
        id: params.id,
        doctorId: params.doctorId,
        expiresAt: params.expiresAt,
        patientName: params.patientName,
        patientAge: params.patientAge,
        preferredLanguage: params.preferredLanguage ?? 'en',
        status: 'WAITING',
      },
    });
  } catch (err) {
    console.error('[sessionRepository] createSession failed:', (err as Error).message);
    return null;
  }
}

/**
 * Updates a session's status.
 * Returns the updated record, or null if DB is unavailable.
 */
export async function updateSessionStatus(
  sessionId: string,
  status: SessionStatus,
): Promise<DoctorSession | null> {
  const db = getPrismaClient();
  if (!db) return null;

  try {
    return await db.doctorSession.update({
      where: { id: sessionId },
      data: { status },
    });
  } catch (err) {
    console.error('[sessionRepository] updateSessionStatus failed:', (err as Error).message);
    return null;
  }
}

/**
 * Marks all expired sessions for a doctor as EXPIRED.
 * Returns count of updated records, or 0 if DB unavailable.
 */
export async function expireOldSessions(doctorId: string): Promise<number> {
  const db = getPrismaClient();
  if (!db) return 0;

  try {
    const result = await db.doctorSession.updateMany({
      where: {
        doctorId,
        expiresAt: { lt: new Date() },
        status: { in: ['WAITING', 'SCANNING'] },
      },
      data: { status: 'EXPIRED' },
    });
    return result.count;
  } catch (err) {
    console.error('[sessionRepository] expireOldSessions failed:', (err as Error).message);
    return 0;
  }
}
